Cleaning/category
soton-data-mining/job-salary-prediction pull request #27
Opened 2017-02-21 23:33 UTC by andreaseliasson

2017-02-26 14:10 UTC, arahayrabedian reviewed
import reordering if you want to be pep8 strict, otherwise LGTM

2017-02-26 14:10 UTC, arahayrabedian commented on src/cleaning_functions.py
> +import re
minor PEP8 reordering recommended.

2017-02-26 15:43 UTC, andreaseliasson commented
@arahayrabedian: fixed pep8 import issue.

2017-02-26 15:44 UTC, arahayrabedian approved these changes

2017-02-26 16:55 UTC, andreaseliasson commented
@arahayrabedian: branch has been rebased on top of master and latest commit reflects the Oldmainmethod.py setup.

2017-02-26 19:25 UTC, arahayrabedian commented
still looks good, haven't run it myself but eyeballing it looks nice.

2017-02-26 22:01 UTC, utkuozbulak commented
Umm, can you help me understand something: 
Note from the first commit:
> For now this function is used to clean the category strings by
removing the 'Jobs' substring. The 'Jobs' is superfluous data which
appears in each category so we can remove `

If, before this conversion there are N unique categories, after this conversion there are same N different categories (removing 'jobs' from each one). Whats the point ? When we encode it having 'job' in the string doesn't matter since everything will be encoded.

Or, were there some categories such as 'Engineering' and 'Engineering Jobs' and with this cleaning we reduced the amount of unique categories ? Is this the case ?

2017-02-26 22:02 UTC, utkuozbulak requested changes
Questions questions

2017-02-28 09:04 UTC, andreaseliasson commented
@utkuozbulak: I see your point. Removing 'Jobs' will not reduce the number of unique categories.

My reasoning for doing this was to reduce the amount of encoding that had to be done. Consequently reducing the amount of bits that had to be used and thus reducing space and possibly run-time.

But if the encoding process doesn't take into account the length of the categories, then we can discard the changes. If so, I will update the branch to only include the minor fixes (we have duplicate 'ContractTime' features).

2017-02-28 19:07 UTC, utkuozbulak commented
Encoding(the way we do it now) doesn't take the amount of bits into account so the from that perspective it won't change but there is no need to discard the change. Let it stay like this, maybe we will end up changing the way we encode and then it might help. Who knows ?

2017-02-28 19:07 UTC, utkuozbulak approved these changes
Okidok

2017-02-28 19:54 UTC, merged